In [1]:
import numpy as np
import os
os.listdir()
k=[]

for i in os.listdir():
    if i.startswith("climate_data_station"):
        a=np.genfromtxt(i,delimiter=',',skip_header=True)
        k.append(a)
k
        

[array([[ 25.,  76.,  99.],
        [ 39.,  65.,  70.],
        [ 59.,  45.,  77.],
        ...,
        [ 95., 100.,  66.],
        [ 75.,  97.,  24.],
        [ 87.,  59.,  81.]]),
 array([[85., 51., 88.],
        [47., 66., 95.],
        [59., 95., 90.],
        ...,
        [99., 62., 58.],
        [70., 71., 91.],
        [92., 39., 76.]]),
 array([[ 93.,  41.,  94.],
        [ 81.,  47.,  98.],
        [ 65.,  71.,  91.],
        ...,
        [ 57.,  91.,  27.],
        [ 51.,  92.,  64.],
        [100.,  32.,  82.]]),
 array([[82., 21., 40.],
        [76., 76., 93.],
        [47., 24., 81.],
        ...,
        [68., 59., 74.],
        [49., 81., 28.],
        [44., 27., 27.]]),
 array([[38., 46., 21.],
        [68., 75., 33.],
        [29., 91., 68.],
        ...,
        [97., 43., 47.],
        [94., 90., 96.],
        [74., 66., 87.]]),
 array([[57., 98., 28.],
        [51., 51., 22.],
        [50., 79., 20.],
        ...,
        [62., 34., 83.],
        [98., 72., 23.],
 

In [3]:
k2 = np.array([ii for i in k for ii in i])
k2
a=np.savetxt("climate_data_added_5.csv",k2,delimiter=',',header='temperature,rainfall,humidity')

In [5]:
k2.shape

(10000, 3)