In [61]:
import numpy as np


In [62]:
climate_data=np.loadtxt('climate_data_added_5.csv',delimiter=',',skiprows=1)
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [63]:
w1=climate_data[0:,:1]
w1

array([[25.],
       [39.],
       [59.],
       ...,
       [99.],
       [70.],
       [92.]])

In [64]:
w1_1=w1*0.3
w1_1

array([[ 7.5],
       [11.7],
       [17.7],
       ...,
       [29.7],
       [21. ],
       [27.6]])

In [65]:
w2=climate_data[0:,1:2]
w2

array([[76.],
       [65.],
       [45.],
       ...,
       [62.],
       [71.],
       [39.]])

In [66]:
w2_2=w2*0.2
w2_2

array([[15.2],
       [13. ],
       [ 9. ],
       ...,
       [12.4],
       [14.2],
       [ 7.8]])

In [67]:
w3=climate_data[0:,2:]
w3

array([[99.],
       [70.],
       [77.],
       ...,
       [58.],
       [91.],
       [76.]])

In [68]:
w3_3=w3*0.5
w3_3

array([[49.5],
       [35. ],
       [38.5],
       ...,
       [29. ],
       [45.5],
       [38. ]])

In [69]:
yeild=w1_1+w2_2+w3_3
yeild

array([[72.2],
       [59.7],
       [65.2],
       ...,
       [71.1],
       [80.7],
       [73.4]])

In [74]:
s=np.append(climate_data,yeild,axis=1)

In [75]:
a=np.savetxt("Result of climate data.csv",s,delimiter=',',header='temperature,rainfall,humidity,yeild of corp')