In [33]:
'''1) Is there any difference in the data type of variables list_ and array_list? 
If there is then write a code to print the data types of both the variables.'''
import numpy as np 
list_ = [ '1' , '2' , '3', '4' , '5' ] 
arraylist = np.array(list_)
print(type(arraylist))
print(type(list_))

<class 'numpy.ndarray'>
<class 'list'>


In [34]:
'''2) Write a code to print the data type of each and every element of both the variables list_ and arra_list.'''
for item in list_:
    print(type(item))
for item in arraylist:
    print(type(item))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [36]:
'''3) Considering the following changes in the variable
array_list: arraylist = np.array(object = list, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and arralist?
If so then print the data types of each and every element present in both the variables, list and arra_list.'''
import numpy as np 
list_ = [ '1' , '2' , '3' , '4', '5' ] 
arraylist = np.array(list_,dtype=int)
for item in list_:
    print(type(item))
for item in arraylist:
    print(type(item))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [43]:
'''import numpy as np num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ] num_array = np.array(object = num_list)
4) Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size'''
import numpy as np 
num_list = np.array([[ 1 , 2 , 3 ] , [ 4 , 5 , 6 ]])
shape=num_list.shape
size=num_list.size
print(shape)
print(size)


(2, 3)
6


In [100]:
'''Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]'''
import numpy as np
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [93]:
'''Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]'''
iden=np.eye(5,5)
print(iden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
import numpy as np
arr=np.arange(1,25).reshape(3,2,4)
print(arr)
print("*"*30)
print(arr[2])
print("*"*30)
print(arr[-1,-1,-1])
print("*"*30)
print(arr[:,:2,1:2])
print("*"*30)
ab=arr[:3,:1]
print(ab)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
******************************
[[17 18 19 20]
 [21 22 23 24]]
******************************
24
******************************
[[[ 2]
  [ 6]]

 [[10]
  [14]]

 [[18]
  [22]]]
******************************
[[[ 1  2  3  4]]

 [[ 9 10 11 12]]

 [[17 18 19 20]]]


In [134]:
import random
random_numbers = [random.randint(1, 100) for _ in range(7)]
print(random_numbers)
import numpy as np
print("*"*30)
u_array = np.empty((2, 5))
print(u_array)
print("*"*30)
lin=np.linspace(1,3,10)
print(lin)
print("*"*30)
hun=np.empty((3,3))
hun.fill(100)
print(hun)

[64, 24, 97, 71, 17, 58, 55]
******************************
[[1.         1.22222222 1.44444444 1.66666667 1.88888889]
 [2.11111111 2.33333333 2.55555556 2.77777778 3.        ]]
******************************
[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]
******************************
[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]
